[package]
name = "scarab"
version = "0.1.0"
edition = "2021"

[dependencies.pyo3]
version = "0.23.3" 
features = ["auto-initialize", "extension-module"]

[dependencies.rocket]
version = "0.5.1"
features = ["secrets"]
